### PR TITLE
WIP: Post inventory DNS handling.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by tomprince** [comment]
@rtucker-mozilla Something like this? (This isn't wired up to anything yet)

**Comment by rtucker-mozilla** [comment]
This looks amazing, @tomprince Thanks!

**Comment by lundjordan** [comment]
@tomprince do we still want this PR?

**Comment by MihaiTabara** [comment]
Note to self: try this next time to validate these changes.

**Pull request closed without merging**
