### PR TITLE
Mount EBS volume on c4 Windows instances

### PR DESCRIPTION
**Pull request by indygreg**
See each commit message for more.

### CODE REVIEW

**Comment by indygreg** [comment]
I should say that I didn't test these commits and am not really sure how to test them. If you teach me how to fish, I'll gladly test them.

**Comment by indygreg** [comment]
Uh, I'm not sure. Is the code in this repository being used to provision EC2 instances today? If it is, then the patches may still be valid. The 2nd patch to not initialize an EBS volume from an AMI should yield substantiate performance wins.

**Comment by tomprince** [comment]
As I understand it, this code is used for provisioning windows workers in buildbot. Since we hope there won't be another ESR52 release, we probably won't be spinning up any other instances, so it isn't worth worrying about this.

Even if we need to do another release, it will probably take more time to validate this change, than the time wasted by not applying this change.

**Comment by indygreg** [comment]
I'm more than happy to let anything related to buildbot rot until it dies naturally. Just as long as that rot doesn't cause major problems. Something being slow on legacy release repos doesn't count as a "major problem" in my mind :)

**Pull request closed without merging**
